# Generated by Django 5.0.3 on 2024-04-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDeMiPre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor'), ('proveedor', 'Proveedor'), ('cliente', 'Cliente')], max_length=20),
        ),
    ]
