# Generated by Django 5.0.3 on 2024-04-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDeMiPre', '0002_alter_usuarios_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='rol',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
