# Generated by Django 5.0.3 on 2024-04-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDeMiPre', '0003_remove_usuarios_rol_alter_usuarios_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(choices=[('comprador', 'Comprador'), ('vendedor', 'Vendedor'), ('proveedor', 'Proveedor'), ('cliente', 'Cliente')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
