# Generated by Django 5.0.3 on 2024-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDeMiPre', '0004_usuarios_rol_alter_usuarios_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(max_length=12),
        ),
    ]
